name: nmap-cprov
version: 1
summary: The Network Mapper
description: The Network Mapper
confinement: strict
grade: stable

apps:
  nmap:
    command: bin/nmap
    plugs: [network-bind, network]
  ncat:
    command: bin/ncat
    plugs: [network-bind, network]
  nping:
    command: bin/nping
    plugs: [network-bind, network]

parts:
  nmap:
    plugin: autotools
    source: https://github.com/nmap/nmap.git
